export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function WebsiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="">
      <header className="w-full text-xl font-bold p-4 text-white text-center bg-black z-[999]">
        This is the header for default site
      </header>
      <main>{children}</main>
      <footer className="text-xl font-bold p-4 text-white text-center bg-black">
        This is the footer for default site
      </footer>
    </div>
  );
}
